### ISSUE TITLE
make viztrace dep more compatible

### ISSUE THREAD

**Issue by copdips** [vpcarlos/profyle#3]
Hello

I found profyle is great as it makes viztracer more easier to use, thanks for the work!

I'm using both viztracer and profyle in the same project, but profyle pin the viztracer to 0.16.2:
https://github.com/vpcarlos/profyle/blob/5d808dfd4c82263b354932a2b121f3c86d4683da/pyproject.toml#L45

Could you please make this less restrictive, maybe 0.16.* ?

**Comment by vpcarlos** [comment]
Thanks for the words!! It's a very good idea, I will do it 👍🏻

**Comment by vpcarlos** [comment]
Deployed
